### ISSUE TITLE
Unhandle Exception on Latest Lib 3.0.3

### ISSUE THREAD

**Issue by ankur4747github** [doghappy/socket.io-client-csharp#228]
CoreCLR Version: 4.700.21.26205
.NET Core Version: 3.1.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at SocketIOClient.Transport.DefaultClientWebSocket.ConnectAsync(Uri uri, CancellationToken cancellationToken)
   at SocketIOClient.Transport.WebSocketTransport.ConnectAsync(Uri uri)
   at SocketIOClient.Transport.TransportRouter.ConnectByWebsocketAsync()
   at SocketIOClient.Transport.TransportRouter.ConnectAsync()
   at SocketIOClient.SocketIO.ConnectAsync()
   at SocketIOClient.SocketIO.ConnectAsync()
   at SocketIOClient.SocketIO.InvokeDisconnect(String reason)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by ankur4747github** [comment]
it's not reproducible.. is there a way that you handle this error in your lib and handle it internally ?... because of this error my application crashed... I already using try-catch but still, my application crashed .. need a solution for the application that crashed..
