### ISSUE TITLE
Unhandled exception in opened handler (SocketIO v2.3.1)

### ISSUE THREAD

**Issue by 23W** [doghappy/socket.io-client-csharp#239]
Hi @doghappy 
Customer sent screenshot with unhandled exception.
![image](https://user-images.githubusercontent.com/11534020/142597587-c259b3c8-7327-4616-8a03-e08033cb08e8.png)
and brief exception text part:

> ************** Exception Text **************
SocketIOClient.Exceptions.InvalidSocketStateException: Connection is not open.
at SocketIOClient.WebSocketClient.ClientWebSocket.\<SendMessageAsync\>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at SocketIOClient.WebSocketClient.ClientWebSocket.\<SendMessageAsync\>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at SocketIOClient.SocketIO.\<OpenedHandler\>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Seems exception occurs in `OpenedHandler` method at attempt to execute `await Socket.SendMessageAsync(msg);`
```
        private async void OpenedHandler(string sid, int pingInterval, int pingTimeout)
        {
            Id = sid;
            _pingInterval = pingInterval;
            string msg = Options.EioHandler.CreateConnectionMessage(Namespace, Options.Query);
            await Socket.SendMessageAsync(msg);
        }
```
Exception was not caught in `OpenedHandler()` or in `OpenedProcessor.Process`, which called this method as delegate.
Can you please give recommendation how this situation is possible and how to fix code in 2.3.1 (this lib version is used in production and should be fixed).

**Comment by doghappy** [comment]
> Seems exception occurs in `OpenedHandler` method at attempt to execute `await Socket.SendMessageAsync(msg);`

If the exception is indeed thrown here, it means that the WebSocket was disconnected shortly after the connection was established, causing some information of socket.io to not be sent.

If this problem occurs by accident, can it be fixed like this?

```cs
        private async void OpenedHandler(string sid, int pingInterval, int pingTimeout)
        {
            Id = sid;
            _pingInterval = pingInterval;
            string msg = Options.EioHandler.CreateConnectionMessage(Namespace, Options.Query);
            try
            {
                throw new Exception("TEST Exception");
                // await Socket.SendMessageAsync(msg).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                ErrorHandler(e.Message);
                await ConnectAsync().ConfigureAwait(false);
            }
        }
```

btw, I will consider adding a better solution to the latest version.

**Comment by 23W** [comment]
@doghappy 
Thank you for the advise, your suggestion seems works well. We age going to update our local fork of your library to fix the issue.

**Comment by doghappy** [comment]
> Thank you for the advise, your suggestion seems works well. We age going to update our local fork of your library to fix the issue.

I suggest you based on this branch https://github.com/doghappy/socket.io-client-csharp/tree/v2.x

**Comment by 23W** [comment]
> > Thank you for the advise, your suggestion seems works well. We age going to update our local fork of your library to fix the issue.
> 
> I suggest you based on this branch https://github.com/doghappy/socket.io-client-csharp/tree/v2.x

Do you mean to make a PR in v2.x branch with this fix?

**Comment by doghappy** [comment]
no.

~I suggest you based on this branch https://github.com/doghappy/socket.io-client-csharp/tree/v2.x~

I suggest you base on this branch https://github.com/doghappy/socket.io-client-csharp/tree/v2.x instead of downloading from the release page.

It is better if you are willing to submit a PR :)

---

btw, I would rather find the real reason, maybe it is the network reason, or something else? Do you have any suggestions?

In v3.x, I added a [retry mechanism](https://github.com/doghappy/socket.io-client-csharp/commit/71425ef31c7f98aea09e339c6c3bbbdcad287d09), I don't know which way is better.

**Comment by DmitryBk** [comment]
Of course, it`s a rare case but I would suggest starting standard reconnection flow for this case
`private async void OpenedHandler(string sid, int pingInterval, int pingTimeout)
{
    try
    {
        Id = sid;
        _pingInterval = pingInterval;
        string msg = Options.EioHandler.CreateConnectionMessage(Namespace, Options.Query);
        await Socket.SendMessageAsync(msg).ConfigureAwait(false);
    }
    catch (Exception e)
    {
        ErrorHandler(e.Message);

        Attempts++;
        await InvokeDisconnectAsync(e.Message).ConfigureAwait(false);
    }
}`

**Comment by doghappy** [comment]
There is an if condition in InvokeDisconnectAsync

https://github.com/doghappy/socket.io-client-csharp/blob/d523efefaaf5f812d560aea4318d533200c10a5e/src/SocketIOClient/SocketIO.cs#L635-L655

When an exception is thrown in OpenedHandler, the value of `Connected` is false

**Comment by DmitryBk** [comment]
It works for me with throw new Exception("TEST Exception");
It seems the `OpenedHandler` is called after the connection is established and after `ConnectedHandler` which set `Connected = true`
