### ISSUE TITLE
I´m getting spammed by error messages

### ISSUE THREAD

**Issue by South2AK** [doghappy/socket.io-client-csharp#357]
I´m getting spammed by this message even though there´s nothing going on in my ocde.

`[monodroid-assembly] typemap: unable to find mapping to a managed type from Java type 'com/android/okhttp/internal/huc/DelegatingHttpsURLConnection'
[monodroid-assembly] typemap: called from
[monodroid-assembly] at Java.Interop.TypeManager.GetJavaToManagedType(String class_name) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Interop/TypeManager.cs:line 228
[monodroid-assembly]    at Java.Interop.TypeManager.CreateInstance(IntPtr handle, JniHandleOwnership transfer, Type targetType) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Interop/TypeManager.cs:line 274
[monodroid-assembly]    at Java.Lang.Object.GetObject(IntPtr handle, JniHandleOwnership transfer, Type type) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:line 303
[monodroid-assembly]    at Java.Lang.Object._GetObject[URLConnection](IntPtr handle, JniHandleOwnership transfer) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:line 289
[monodroid-assembly]    at Java.Lang.Object.GetObject[URLConnection](IntPtr handle, JniHandleOwnership transfer) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:line 281
[monodroid-assembly]    at Java.Net.URL.OpenConnection() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.Net.URL.cs:line 373
[monodroid-assembly]    at Xamarin.Android.Net.AndroidMessageHandler.DoSendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 435
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<DoSendAsync>d__127](<DoSendAsync>d__127& stateMachine)
[monodroid-assembly]    at Xamarin.Android.Net.AndroidMessageHandler.DoSendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[monodroid-assembly]    at Xamarin.Android.Net.AndroidMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 397
[monodroid-assembly]    at System.Net.Http.Metrics.MetricsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[monodroid-assembly]    at System.Net.Http.HttpMessageHandlerStage.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[monodroid-assembly]    at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[monodroid-assembly]    at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[monodroid-assembly]    at System.Net.Http.HttpClient.<>n__0(HttpRequestMessage request, CancellationToken cancellationToken)
[monodroid-assembly]    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<<SendAsync>g__Core|83_0>d](<<SendAsync>g__Core|83_0>d& stateMachine)
[monodroid-assembly]    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[monodroid-assembly]    at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
[monodroid-assembly]    at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[monodroid-assembly]    at SocketIOClient.Transport.Http.DefaultHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[monodroid-assembly]    at SocketIOClient.Transport.Http.HttpPollingHandler.SendAsync(HttpRequestMessage req, CancellationToken cancellationToken)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<SendAsync>d__16](<SendAsync>d__16& stateMachine)
[monodroid-assembly]    at SocketIOClient.Transport.Http.HttpPollingHandler.SendAsync(HttpRequestMessage req, CancellationToken cancellationToken)
[monodroid-assembly]    at SocketIOClient.Transport.Http.HttpTransport.ConnectAsync(Uri uri, CancellationToken cancellationToken)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<ConnectAsync>d__9](<ConnectAsync>d__9& stateMachine)
[monodroid-assembly]    at SocketIOClient.Transport.Http.HttpTransport.ConnectAsync(Uri uri, CancellationToken cancellationToken)
[monodroid-assembly]    at SocketIOClient.SocketIO.<>c__DisplayClass88_0.<<ConnectInBackground>b__0>d.MoveNext()
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SocketIOClient.SocketIO.<>c__DisplayClass88_0.<<ConnectInBackground>b__0>d, SocketIOClient, Version=3.1.1.0, Culture=neutral, PublicKeyToken=c9a3629195a82104]].ExecutionContextCallback(Object s)
[monodroid-assembly]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SocketIOClient.SocketIO.<>c__DisplayClass88_0.<<ConnectInBackground>b__0>d, SocketIOClient, Version=3.1.1.0, Culture=neutral, PublicKeyToken=c9a3629195a82104]].MoveNext(Thread threadPoolThread)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SocketIOClient.SocketIO.<>c__DisplayClass88_0.<<ConnectInBackground>b__0>d, SocketIOClient, Version=3.1.1.0, Culture=neutral, PublicKeyToken=c9a3629195a82104]].MoveNext()
[monodroid-assembly]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[monodroid-assembly]    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishContinuations()
[monodroid-assembly]    at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(VoidTaskResult result)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(Task`1 task, VoidTaskResult result)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
[monodroid-assembly]    at SocketIOClient.SocketIO.InitTransportAsync()
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SocketIOClient.SocketIO.<InitTransportAsync>d__84, SocketIOClient, Version=3.1.1.0, Culture=neutral, PublicKeyToken=c9a3629195a82104]].ExecutionContextCallback(Object s)
[monodroid-assembly]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SocketIOClient.SocketIO.<InitTransportAsync>d__84, SocketIOClient, Version=3.1.1.0, Culture=neutral, PublicKeyToken=c9a3629195a82104]].MoveNext(Thread threadPoolThread)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[SocketIOClient.SocketIO.<InitTransportAsync>d__84, SocketIOClient, Version=3.1.1.0, Culture=neutral, PublicKeyToken=c9a3629195a82104]].MoveNext()
[monodroid-assembly]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[monodroid-assembly]    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishContinuations()
[monodroid-assembly]    at System.Threading.Tasks.Task`1[[SocketIOClient.Transport.TransportProtocol, SocketIOClient, Version=3.1.1.0, Culture=neutral, PublicKeyToken=c9a3629195a82104]].TrySetResult(TransportProtocol result)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[SocketIOClient.Transport.TransportProtocol, SocketIOClient, Version=3.1.1.0, Culture=neutral, PublicKeyToken=c9a3629195a82104]].SetExistingTaskResult(Task`1 task, TransportProtocol result)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[SocketIOClient.Transport.TransportProtocol, SocketIOClient, Version=3.1.1.0, Culture=neutral, PublicKeyToken=c9a3629195a82104]].SetResult(TransportProtocol result)
[monodroid-assembly]    at SocketIOClient.SocketIO.GetProtocolAsync()
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[SocketIOClient.Transport.TransportProtocol, SocketIOClient, Version=3.1.1.0, Culture=neutral, PublicKeyToken=c9a3629195a82104],[SocketIOClient.SocketIO.<GetProtocolAsync>d__91, SocketIOClient, Version=3.1.1.0, Culture=neutral, PublicKeyToken=c9a3629195a82104]].ExecutionContextCallback(Object s)
[monodroid-assembly]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[SocketIOClient.Transport.TransportProtocol, SocketIOClient, Version=3.1.1.0, Culture=neutral, PublicKeyToken=c9a3629195a82104],[SocketIOClient.SocketIO.<GetProtocolAsync>d__91, SocketIOClient, Version=3.1.1.0, Culture=neutral, PublicKeyToken=c9a3629195a82104]].MoveNext(Thread threadPoolThread)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[SocketIOClient.Transport.TransportProtocol, SocketIOClient, Version=3.1.1.0, Culture=neutral, PublicKeyToken=c9a3629195a82104],[SocketIOClient.SocketIO.<GetProtocolAsync>d__91, SocketIOClient, Version=3.1.1.0, Culture=neutral, PublicKeyToken=c9a3629195a82104]].MoveNext()
[monodroid-assembly]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[monodroid-assembly]    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishContinuations()
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishStageThree()
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishStageTwo()
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
[monodroid-assembly]    at System.Threading.Tasks.Task.Finish(Boolean userDelegateExecute)
[monodroid-assembly]    at System.Threading.Tasks.Task.TrySetException(Object exceptionObject)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetException(Exception exception, Task`1& taskField)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetException(Exception exception)
[monodroid-assembly]    at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpClient.<GetStringAsyncCore>d__41, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ExecutionContextCallback(Object s)
[monodroid-assembly]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpClient.<GetStringAsyncCore>d__41, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext(Thread threadPoolThread)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpClient.<GetStringAsyncCore>d__41, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
[monodroid-assembly]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[monodroid-assembly]    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishContinuations()
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishStageThree()
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishStageTwo()
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
[monodroid-assembly]    at System.Threading.Tasks.Task.Finish(Boolean userDelegateExecute)
[monodroid-assembly]    at System.Threading.Tasks.Task.TrySetException(Object exceptionObject)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].SetException(Exception exception, Task`1& taskField)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].SetException(Exception exception)
[monodroid-assembly]    at Xamarin.Android.Net.AndroidMessageHandler.DoSendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 429
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[Xamarin.Android.Net.AndroidMessageHandler.<DoSendAsync>d__127, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].ExecutionContextCallback(Object s)
[monodroid-assembly]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[Xamarin.Android.Net.AndroidMessageHandler.<DoSendAsync>d__127, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].MoveNext(Thread threadPoolThread)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[Xamarin.Android.Net.AndroidMessageHandler.<DoSendAsync>d__127, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].MoveNext()
[monodroid-assembly]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[monodroid-assembly]    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishContinuations()
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishStageThree()
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishStageTwo()
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
[monodroid-assembly]    at System.Threading.Tasks.Task.Finish(Boolean userDelegateExecute)
[monodroid-assembly]    at System.Threading.Tasks.Task.TrySetException(Object exceptionObject)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].SetException(Exception exception, Task`1& taskField)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].SetException(Exception exception)
[monodroid-assembly]    at Xamarin.Android.Net.AndroidMessageHandler.DoProcessRequest(HttpRequestMessage request, URL javaUrl, HttpURLConnection httpConnection, CancellationToken cancellationToken, RequestRedirectionState redirectState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 723
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[Xamarin.Android.Net.AndroidMessageHandler.<DoProcessRequest>d__136, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].ExecutionContextCallback(Object s)
[monodroid-assembly]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[Xamarin.Android.Net.AndroidMessageHandler.<DoProcessRequest>d__136, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].MoveNext(Thread threadPoolThread)
[monodroid-assembly]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[Xamarin.Android.Net.AndroidMessageHandler.<DoProcessRequest>d__136, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].MoveNext()
[monodroid-assembly]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[monodroid-assembly]    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishContinuations()
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishStageThree()
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishStageTwo()
[monodroid-assembly]    at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
[monodroid-assembly]    at System.Threading.Tasks.Task.Finish(Boolean userDelegateExecute)
[monodroid-assembly]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[monodroid-assembly]    at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
[monodroid-assembly]    at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
[monodroid-assembly]    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[monodroid-assembly]    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()`

**Comment by LevyShang** [comment]
in your log, i find this 'Release/net8.0' , but this project target is .NET Standard 2 , i think you must check your project target
