### ISSUE TITLE
How to reconnect when disconnected?

### ISSUE THREAD

**Issue by mrx-bell** [doghappy/socket.io-client-csharp#58]
How auto reconnect . Thanks

**Comment by doghappy** [comment]
```cs
private static async void Socket_OnDisconnected(object sender, string e)
{
    Console.WriteLine("disconnect: " + e);
    var client = sender as SocketIO;
    await client.ConnectAsync();
}
```

**Comment by mrx-bell** [comment]
Thanks . But i recived error: System.Net.WebSockets.WebSocketException: 'Unable to connect to the remote server'

**Comment by doghappy** [comment]
Is this exception thrown on the first connection?

**Comment by mrx-bell** [comment]
When i stop server then start again i recived this error .

**Comment by mrx-bell** [comment]
@doghappy How i can add this option : `{secure: true,
		reconnection: true,
		reconnectionDelay: 1000,
		reconnectionDelayMax: 5000,
		transports: ['websocket']}`

**Comment by mrx-bell** [comment]
@doghappy Sorry friend . I'm newbie on C#. Very thank friend.

**Comment by doghappy** [comment]
Sorry, the option you provided has not been implemented. But you can try the following code:

```cs
static SocketIO _socket;

static async Task Main(string[] args)
{
    var uri = new Uri("http://localhost:11000/nsp");
    _socket = new SocketIO(uri, new SocketIOOptions
    {
        Query = new Dictionary<string, string>
        {
            {"token", "io" }
        }
    });

    _socket.OnDisconnected += Socket_OnDisconnected;
    await _socket.ConnectAsync();
    
    _socket.On("hi", response =>
    {
        Console.WriteLine($"server: {response.GetValue<string>()}");
    });

    await socket.EmitAsync("hi", "SocketIOClient.Sample");
}

private static async void Socket_OnDisconnected(object sender, string e)
{
    Console.WriteLine("disconnect: " + e);
    //var client = sender as SocketIO;
    for (int i = 1; i <= 10; i++)
    {
        try
        {
            await _socket.ConnectAsync();
            // await client.ConnectAsync();
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
            Console.WriteLine($"Wait {i} s...");
            await Task.Delay(TimeSpan.FromSeconds(i));
        }
    }
}
```

**Comment by mrx-bell** [comment]
@doghappy Thanks so much. I want wait until have connect. This is only wait 10s how i can handle until have connect again.

**Comment by doghappy** [comment]
It will retry 10 times and wait for `i` seconds after failure.

```cs
    for (int i = 1; i <= 10; i++)
    {
        try
        {
            await _socket.ConnectAsync();
            // await client.ConnectAsync();
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
            Console.WriteLine($"Wait {i} s...");
            await Task.Delay(TimeSpan.FromSeconds(i));
        }
    }
```

**Comment by mrx-bell** [comment]
@doghappy Thanks but i will retry until have connect. I can inc i to 10000 +  but i want using why loop. Sorry i'm newbie on C#.

**Comment by doghappy** [comment]
I made a mistake and forgot to `break`. maybe the following code suits you better

```cs
            while (true)
            {
                try
                {
                    await client.ConnectAsync();
                    break;
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    await Task.Delay(1000);
                }
            }
```

**Comment by mrx-bell** [comment]
@doghappy . Thanks for help . You save my life. Thanks again!

**Comment by doghappy** [comment]
I have implemented the automatic reconnect function

https://github.com/doghappy/socket.io-client-csharp/pull/60

If you upgrade to the latest preview version `2.0.2-alpha.2`, you will not need to listen to the `OnDisconnected` event and write reconnect logic code.

In the latest preview version, `Reconnection` is enabled by default. If you want to use your own logical to reconnect, you can disable `Reconnection`.

```cs
            var client = new SocketIO(Uri, new SocketIOOptions
            {
                Reconnection = false
            });
```

**Comment by adeiry** [comment]
I developed my project on Windows 7 and I used version 2.0.0 and everything worked fine on Windows 7, but when I created the executable file and install it on windows 8 or 10 the socket won't work as it should. What should I do?

**Comment by adeiry** [comment]
In my project, I have a button that connects the socket at first, do some stuff then disconnects the socket. When I clicked the button, the first time it worked but in the second time the socket took a long time then it won't connect and I had an exception: 

> Unable to connect to the remote server
A task was canceled.

Do you have any idea why?? I am so confused!

`try
                        {
                            await socketCall.ConnectAsync();
                        }
                        catch (Exception ex)
                        {
                            Trace.WriteLine("RequestCall Connect to socket call exception: " + ex.Message);
                        }`

**Comment by doghappy** [comment]
@adeiry Can you provide more code to reproduce? Or create a reproducible mini repository?

**Comment by adeiry** [comment]
@doghappy My project is pretty long and complicated so I will try here to explain to you what I'm doing in this particular scenario.

```
public void CallButton_Clicked(User u, string callType)
        {
            try
            {
		// socketManager is an instance of the class SocketManager
		// SocketManager is the class that contains everything about the soket, events and emits 
                if (GlobalVariables.socketManager != null)
                {
                    // Request the call
                    GlobalVariables.socketManager.RequestCall(u, callType);
                }

                // Do other stuff
		// Show the calling screen              
                // Play call ringtone
                
            }
            catch (Exception ex)
            {
                Trace.WriteLine("CallButton_Clicked exception: " + ex.Message);
            }
        }
```

Now in the SocketManager class, I created the RequestCall function to connect to the socket

```
public async void RequestCall(User dest_u, string type)
        {
            // Now the logged in user want to request a call

            // Check parameters
            bool isFailed = true;
            if(dest_u != null)
            {
                if(dest_u.autocoding != null && dest_u.autocoding != "")
                {
                    if(type != null && type != "")
                    {
                        isFailed = false;                      
                    }
                }
            }

            if (!isFailed)
            {
                // Specify the type and the direction of the call
                if (type == "audio") _callType = "OutgoingAudioCall";
                if (type == "video") _callType = "OutgoingVideoCall";
                _callDirection = "outgoing";

                // Create the socket object
                _socketObject = null;
                if (_user != null && _callType != "")
                {
                    _socketObject = new SocketObject(_user.dev_uuid, _user.autocoding, _user.room_uid, dest_u.autocoding, _callType, "win", "", "", "", "", "");
                }

                try
                    {
                        // Connect to the call socket 
                        await socketCall.ConnectAsync();

                        // Play dial ringtone
                        SoundManager.PlaySound(SoundManager.SoundEffect.dial);
                    }
                    catch (Exception ex)
                    {
                        Trace.WriteLine("RequestCall Connect to socket call exception: " + ex.Message);
                    }
            }
            else
            {
                // Wrong parameters we can't request a call
                // TODO: Display a warning alert
                Trace.WriteLine("Wrong parameters we can't request a call");
            }
        }
```

When the user wants to end the call he clicked another button to close the current instance then disconnect the socket.

```
public async void EndTheCall()
        {
            bool instanceExist = false;

            // Check if there is a current call opened
            if (roomInstance != null && socketCall.Connected)
            {
                if (roomInstance.room_uid != null && roomInstance.room_uid != "")
                {
                    instanceExist = true;
                }
            }

            if (instanceExist)
            {
                try
                {
                    if (_socketObject != null && _socketObject.my_uuid == _user.autocoding)
                    {
                        await socketCall.EmitAsync("close_inst", _socketObject);
                    }
                }
                catch(Exception ex)
                {
                    Trace.WriteLine("SocketManager Emit close_inst Exception: " + ex.Message);
                }
            }
            else
            {
                // Stop ringtones
                if (SoundManager.player != null)
                {
                    SoundManager.player.Stop();
                }

                // Complete the close handshake
                EngineManager.CloseHandshake();
            }

            // Clear the socket object
            _socketObject = null;
        }
```

```
// When call is closed or cancelled
                socketCall.On("inst_closed", response =>
                {
                    Trace.WriteLine("the call is cancelled " + response.ToString());

                    SocketObject obj = response.GetValue<SocketObject>();

                    if (roomInstance.room_uid == obj.inst_ruid)
                    {
                        // Check if the socket call is connected 
                	if (socketCall.Connected)
                	{
                    		try
                    		{
                        		// Disconnect the socket call
                        		await socketCall.DisconnectAsync();
                    		}
                    		catch (Exception ex)
                    		{
                        		Trace.WriteLine("SocketManager DisconnectSocketCall() exception: " + ex.Message);
                    		}
                	}

                        // Stop ringtones
                        if (SoundManager.player != null)
                        {
                            SoundManager.player.Stop();
                        }

                        // Complete the close handshake
                        EngineManager.CloseHandshake();

                    }
                });
```

I hope I made it clear, thank you very much for your help.

**Comment by doghappy** [comment]
@adeiry Thank you for the code, but I still haven't found any problems.
Can I access your socket.io service? And can you provide a runnable github repository with no secrets and less code?

**Comment by adeiry** [comment]
@doghappy I can't share the code with you, I don't have the permission to do that.
This is the exception I get. I hope you can help me.

```
at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.get_SecureStream()
   at System.Net.Security.SslStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.Managed.ManagedWebSocket.<SendFrameFallbackAsync>d__56.MoveNext()

```

```
at System.Net.WebSockets.Managed.ManagedWebSocket.<SendFrameFallbackAsync>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SocketIOClient.WebSocketClient.ClientWebSocket.<SendMessageAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SocketIOClient.SocketIO.<EmityAsync>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SocketIOClient.SocketIO.<EmitAsync>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ViboCallWindowsApp.Managers.SocketManager.<<Execute>b__13_6>d.MoveNext() in C:\Production\Work\ViboCallWindowsApp\ViboCallWindowsApp\ViboCallWindowsApp\Managers\SocketManager.cs:line 153
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```

**Comment by doghappy** [comment]
@adeiry  Can you share your NuGET dependencies about the SocketIOClient node?

**Comment by adeiry** [comment]
@doghappy  I'm using SocketIOClient version 2.0.0. The target framework is .NET Framework 4.7.2 and I'm working on windows 7.

![image](https://user-images.githubusercontent.com/9880387/88257555-a4e0ac80-ccc6-11ea-9857-f346ba2e5bc4.png)

**Comment by doghappy** [comment]
@adeiry try update to 2.0.2.3

**Comment by adeiry** [comment]
@doghappy I updated it but then the socket doesn't work on windows 7 so I used your project for windows 7, I put it in my solution and I reference it to my project. The problem is gone but still, it took a long time to connect again to the socket. Any ideas why?

**Comment by doghappy** [comment]
Please do not use the `windows7` branch source code, when the server is disconnected, the `State` will not be changed

I created a new .NET Framework program, running on Windows 7, I did not get any exception (PlatformNotSupportedException), on Windows 7, I installed .NET Framework 4.8 Runtime

```cs
            var uri = new Uri("http://doghappy.wang:11000");
            var socket = new SocketIO(uri, new SocketIOOptions
            {
                Query = new Dictionary<string, string>
                {
                    {"token", "io" }
                }
            });
            await socket.ConnectAsync();

            socket.On("hi", response =>
            {
                Console.WriteLine($"server: {response.GetValue<string>()}");
            });

            await Task.Delay(2000);
            await socket.EmitAsync("hi", "1");
            await socket.EmitAsync("sever disconnect", true);
            await Task.Delay(2000);
            await socket.EmitAsync("hi", "2");
```

![image](https://user-images.githubusercontent.com/20038914/88276102-15acb680-cd11-11ea-97af-51fc96cc79c8.png)

**Comment by adeiry** [comment]
@doghappy thank you very much for everything you did to help me, so much appreciated. I will try again and hope everything will work.

**Comment by doghappy** [comment]
The branch windows7 refers to `System.Net.WebSockets.Client.Managed`. When the server disconnects the WebSocket, the `State` will not be changed. It caused a new problem: it took a long time to connect again to the socket

`System.Net.WebSockets.Client.Managed` supports Windows 7, branch `windows7` to use it as WebSocketClient

**Comment by doghappy** [comment]
> @doghappy thank you very much for everything you did to help me, so much appreciated. I will try again and hope everything will work.

sorry, you don't have to try, it will still throw an exception.

**Comment by doghappy** [comment]
Please transfer to https://github.com/doghappy/socket.io-client-csharp/issues/70

**Comment by doghappy** [comment]
@adeiry  please install [SocketIOClient.NetFx](https://www.nuget.org/packages/SocketIOClient.NetFx)
