### ISSUE TITLE
Collection was modified

### ISSUE THREAD

**Issue by dawalters99** [doghappy/socket.io-client-csharp#80]
```ERROR Application: API Test.exe
CoreCLR Version: 4.700.20.26901
.NET Core Version: 3.1.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at SocketIOClient.SocketIO.EmityCoreAsync(String eventName, Int32 packetId, String data)
   at SocketIOClient.SocketIO.EmitAsync(String eventName, Action`1 ack, Object[] data)
   at Wolf.Net.Client.WolfClient.Emit[T](Packet packet, Int32 attempt) in J:\My Projects\Wolf recodes\Wolf.Net\Wolf.Net\Client\WolfClient.cs:line 140
   at Wolf.Net.WolfBot.SendMessageAsync(Int32 recipient, Object content, MessageType messageType) in J:\My Projects\Wolf recodes\Wolf.Net\Wolf.Net\Helpers\WolfBot.MessageHelper.cs:line 43
   at Wolf.Net.Entities.Messages.Message.SendMessageAsync(Object content) in J:\My Projects\Wolf recodes\Wolf.Net\Wolf.Net\Entities\Messages\Message.cs:line 111
   at API_Test.Commands.Class1.Default(String m) in J:\My Projects\Wolf recodes\API Test\API Test\Commands\Class1.cs:line 17
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

The above error continues to happen when the client is under extremely heavy load, 
I believe it is how you have the "internal List<byte[]> OutGoingBytes { get; private set; }", would it not be wise to provide an Bytes list via the emit methods instead of a global out going bytes?

**Comment by doghappy** [comment]
How do I reproduce? thank

**Comment by dewwalters** [comment]
I have not found a reliable way to replicate this, I just know its been happening a lot lately, and it typically happens when arabic users put my bot under a large load

**Comment by doghappy** [comment]
Thanks for the feedback, I have fixed it. 

commit: https://github.com/doghappy/socket.io-client-csharp/commit/2b53cc1a55f0bbab28e68ca376e836760203eb99
