### ISSUE TITLE
Sudden reconnection exception

### ISSUE THREAD

**Issue by adversinc** [doghappy/socket.io-client-csharp#93]
I'm connecting to an unreliable SocketIO server. We've managed to catch the initial connection exceptions, but I get the following uncaught exception during the work from time to time:

```
System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server.
   at SocketIOClient.NetFx.WebSocketClient.WebSocketSharpClient.<ConnectAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SocketIOClient.SocketIO.<ConnectCoreAsync>d__88.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SocketIOClient.SocketIO.<SocketIO_OnDisconnected>d__103.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

How (and where) to wrap it to try/catch as well? Thank you!

**Comment by adversinc** [comment]
Reported and found this can be fixed by changing SocketIO.SocketIO_OnDisconnected:

catch (ConnectException ex)
to
catch (Exception ex)

**Comment by doghappy** [comment]
Thanks for your feedback, I have fixed it.

Please upgrade from NuGet.
